A Dockerfile to test F* and Everest with various OCaml versions
Successes: 4.12.0, 4.11.2, 4.10.2, 4.09.1, 4.08.1

Failure: 4.07.1, because of EverParse/3d:
  File "Hashing.ml", line 12, characters 2-20:
  Error: Unbound value Bytes.set_int32_be